name: ci-workflow

on:
  workflow_call:
    inputs:
      DOCKER_CONTEXT:
        required: true
        type: string
      DOCKER_FILE:
        required: true
        type: string
      DOCKER_IMAGE_NAME:
        # required: true
        type: string
    secrets:
      DOCKER_REGISTRY:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |
          npm ci
      - name: Build the app
        env:
          CI: ""
        run: |
          npm run build:ci
      - name: Run Tests
        run: |
          npm run test

  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      pull-requests: read
      checks: write
      issues: write
      statuses: write
      deployments: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.DOCKER_CONTEXT }}
          file: ${{ inputs.DOCKER_FILE }}
          push: false
