name: hello-world-ci.yml

on:
  push:
    branches:
      - main

jobs:
  CI:
    uses: ./.github/workflows/ci-workflow.yml
    with:
      DOCKER_CONTEXT: .
      DOCKER_FILE: ./Dockerfile
      DOCKER_IMAGE_NAME: hello-world-react
    secrets: inherit
