name: hello-world-ci.yml

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches-ignore:
      - master
      - main
    paths:
      - ./**
      - .github/workflows/hello-world-ci.yml
      - trigger.txt

jobs:
  CI:
    uses: ./.github/workflows/ci-workflow.yml
    with:
      DOCKER_CONTEXT: .
      DOCKER_FILE: ./Dockerfile
      DOCKER_IMAGE_NAME: hello-world-react
    secrets: inherit
